services:

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - TZ=Europe/Madrid
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - rabbitmq
      - minio
    networks:
      - datalake


  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data
    networks:
      - datalake


  mc-init:
    image: minio/mc:RELEASE.2023-03-20T17-17-53Z
    container_name: mc-init
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set minio http://minio:9000 minio minio123; do
        echo 'Waiting for MinIO to be ready...';
        sleep 1;
      done;

      /usr/bin/mc mb --ignore-existing minio/raw-ingestion-zone;
      /usr/bin/mc mb --ignore-existing minio/clean-zone;
      /usr/bin/mc mb --ignore-existing minio/access-zone;

      echo 'MinIO buckets ready';
      exit 0;
      "
    networks:
      - datalake


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - datalake


  rabbitmq-init:
    image: rabbitmq:3-management
    container_name: rabbitmq-init
    depends_on:
      - rabbitmq
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for RabbitMQ...';

      sleep 10;

      until rabbitmqadmin -H rabbitmq -P 15672 -u guest -p guest list queues > /dev/null 2>&1; do
        echo 'Waiting for RabbitMQ Management API...';
        sleep 2;
      done;

      echo 'Creating RabbitMQ queues...';

      rabbitmqadmin -H rabbitmq -P 15672 -u guest -p guest declare queue name=air_queue durable=false;
      rabbitmqadmin -H rabbitmq -P 15672 -u guest -p guest declare queue name=weather_queue durable=false;

      echo 'RabbitMQ queues ready';
      exit 0;
      "
    networks:
      - datalake


volumes:
  n8n_data:
  minio_data:
  rabbitmq_data:


networks:
  datalake: